Start testing: Mar 18 14:48 AEST
----------------------------------------------------------
1/3 Testing: example_2_urdf_xacro
1/3 Test: example_2_urdf_xacro
Command: "/usr/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_urdf_xacro.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml" "--junit-prefix=arduino_hardware_controller"
Directory: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller
"example_2_urdf_xacro" start time: Mar 18 14:48 AEST
Output:
----------------------------------------------------------
-- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
 - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_urdf_xacro.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml --junit-prefix=arduino_hardware_controller
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/arduino_hardware_controller/ament_cmake_pytest/example_2_urdf_xacro/.cache
rootdir: /home/nwhit210/omnicar_2_ws
plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
collected 1 item

../../src/arduino_controller/test/test_urdf_xacro.py F                   [100%]

=================================== FAILURES ===================================
_______________________________ test_urdf_xacro ________________________________

    def test_urdf_xacro():
        # General Arguments
        description_package = "arduino_hardware_controller"
        description_file = "diffbot.urdf.xacro"
    
        description_file_path = os.path.join(
            get_package_share_directory(description_package), "urdf", description_file
        )
    
        (_, tmp_urdf_output_file) = tempfile.mkstemp(suffix=".urdf")
    
        # Compose `xacro` and `check_urdf` command
        xacro_command = (
            f"{shutil.which('xacro')}" f" {description_file_path}" f" > {tmp_urdf_output_file}"
        )
        check_urdf_command = f"{shutil.which('check_urdf')} {tmp_urdf_output_file}"
    
        # Try to call processes but finally remove the temp file
        try:
            xacro_process = subprocess.run(
                xacro_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True
            )
    
>           assert xacro_process.returncode == 0, " --- XACRO command failed ---"
E           AssertionError:  --- XACRO command failed ---
E           assert 2 == 0
E            +  where 2 = CompletedProcess(args='/opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share...nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro\n').returncode

../../src/arduino_controller/test/test_urdf_xacro.py:62: AssertionError
- generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml -
=========================== short test summary info ============================
FAILED ../../src/arduino_controller/test/test_urdf_xacro.py::test_urdf_xacro
============================== 1 failed in 0.23s ===============================
-- run_test.py: return code 1
-- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/example_2_urdf_xacro.xunit.xml'
<end of output>
Test time =   0.91 sec
----------------------------------------------------------
Test Failed.
"example_2_urdf_xacro" end time: Mar 18 14:48 AEST
"example_2_urdf_xacro" time elapsed: 00:00:00
----------------------------------------------------------

2/3 Testing: view_example_2_launch
2/3 Test: view_example_2_launch
Command: "/usr/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_view_robot_launch.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml" "--junit-prefix=arduino_hardware_controller"
Directory: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller
"view_example_2_launch" start time: Mar 18 14:48 AEST
Output:
----------------------------------------------------------
-- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
 - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_view_robot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/arduino_hardware_controller/ament_cmake_pytest/view_example_2_launch/.cache
rootdir: /home/nwhit210/omnicar_2_ws
plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
collected 1 item

../../src/arduino_controller/test/test_view_robot_launch.py F            [100%]

=================================== FAILURES ===================================
_____________________ launch tests: test_view_robot_launch _____________________

----------------------------- Captured stdout call -----------------------------
[INFO] [launch]: All log files can be found below /home/nwhit210/.ros/log/2025-03-18-14-48-39-727507-nwhit210-2717
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro prefix:=""
Captured stderr output: error: package not found: "package 'ros2_control_demo_description' not found, searching: ['/home/nwhit210/omnicar_2_ws/install/omnicar', '/home/nwhit210/omnicar_2_ws/install/mecanum_drive_controller', '/home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller', '/opt/ros/humble']"
when processing file: /home/nwhit210/omnicar_2_ws/install/arduino_hardware_controller/share/arduino_hardware_controller/urdf/diffbot.urdf.xacro

Processes under test stopped before tests completed
- generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml -
=========================== short test summary info ============================
FAILED ../../src/arduino_controller/test/test_view_robot_launch.py::test_view_robot_launch
============================== 1 failed in 0.36s ===============================
-- run_test.py: return code 1
-- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/view_example_2_launch.xunit.xml'
<end of output>
Test time =   0.96 sec
----------------------------------------------------------
Test Failed.
"view_example_2_launch" end time: Mar 18 14:48 AEST
"view_example_2_launch" time elapsed: 00:00:00
----------------------------------------------------------

3/3 Testing: run_example_2_launch
3/3 Test: run_example_2_launch
Command: "/usr/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml" "--package-name" "arduino_hardware_controller" "--output-file" "/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch.txt" "--command" "/usr/bin/python3" "-u" "-m" "pytest" "/home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_diffbot_launch.py" "-o" "cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache" "--junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml" "--junit-prefix=arduino_hardware_controller"
Directory: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller
"run_example_2_launch" start time: Mar 18 14:48 AEST
Output:
----------------------------------------------------------
-- run_test.py: invoking following command in '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller':
 - /usr/bin/python3 -u -m pytest /home/nwhit210/omnicar_2_ws/src/arduino_controller/test/test_diffbot_launch.py -o cache_dir=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache --junit-xml=/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml --junit-prefix=arduino_hardware_controller
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/arduino_hardware_controller/ament_cmake_pytest/run_example_2_launch/.cache
rootdir: /home/nwhit210/omnicar_2_ws
plugins: ament-xmllint-0.12.11, ament-pep257-0.12.11, ament-flake8-0.12.11, launch-testing-1.0.7, launch-testing-ros-0.19.8, ament-lint-0.12.11, ament-copyright-0.12.11, cov-3.0.0, colcon-core-0.19.0
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/usr/lib/python3/dist-packages/_pytest/python.py:200: in pytest_collect_file
    module: Module = ihook.pytest_pycollect_makemodule(path=path, parent=parent)
/usr/lib/python3/dist-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:83: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:193: in pytest_pycollect_makemodule
    entrypoint = find_launch_test_entrypoint(path)
/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py:186: in find_launch_test_entrypoint
    module = path.pyimport()
/usr/lib/python3/dist-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
../../src/arduino_controller/test/test_diffbot_launch.py:43: in <module>
    from ros2_control_demo_testing.test_utils import (
E   ModuleNotFoundError: No module named 'ros2_control_demo_testing'
- generated xml file: /home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml -
=========================== short test summary info ============================
ERROR ../.. - ModuleNotFoundError: No module named 'ros2_control_demo_testing'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.28s ===============================
-- run_test.py: return code 2
-- run_test.py: verify result file '/home/nwhit210/omnicar_2_ws/build/arduino_hardware_controller/test_results/arduino_hardware_controller/run_example_2_launch.xunit.xml'
<end of output>
Test time =   1.01 sec
----------------------------------------------------------
Test Failed.
"run_example_2_launch" end time: Mar 18 14:48 AEST
"run_example_2_launch" time elapsed: 00:00:01
----------------------------------------------------------

End testing: Mar 18 14:48 AEST

pytest =   2.87 sec*proc

